function Ke = KE_func(in1,in2)
%KE_FUNC
%    KE = KE_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    11-May-2020 12:35:37

%Compass Gait Configuration file. Only needs state as inputs, parameters are already substituted in
Isz = in2(:,1);
Mh = in2(:,2);
Ms = in2(:,3);
a = in2(:,4);
b = in2(:,5);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
t2 = cos(x4);
t3 = a+b;
t4 = x3+x4;
t5 = Isz.*2.0;
t6 = Ms.*2.0;
t7 = a.*2.0;
t8 = b.^2;
t9 = cos(t4);
t10 = sin(t4);
t11 = Mh+t6;
t12 = a+t3;
t13 = Mh.*t3;
t15 = b.*t2.*t3.*t6;
t16 = Ms.*b.*t2.*t3.*-2.0;
t14 = Ms.*t12;
t17 = t13+t14;
Ke = (x8.^2.*(Isz+Ms.*t8))./2.0+(x7.^2.*(t5+t16+t3.*t13+Ms.*(t8.*2.0+a.*t7+b.*t7)))./2.0-x5.*(x7.*(t17.*cos(x3)-Ms.*b.*t9)-Ms.*b.*t9.*x8)-x6.*(x7.*(t17.*sin(x3)-Ms.*b.*t10)-Ms.*b.*t10.*x8)+(t11.*x5.^2)./2.0+(t11.*x6.^2)./2.0+(x7.*x8.*(t5+t16+t6.*t8))./2.0;
