function posCoM = COM_pos_func(in1,in2)
%COM_POS_FUNC
%    POSCOM = COM_POS_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    11-May-2020 12:35:38

%Compass Gait Configuration file. Only needs state as inputs, parameters are already substituted in
Mh = in2(:,2);
Ms = in2(:,3);
a = in2(:,4);
b = in2(:,5);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = a+b;
t3 = x3+x4;
t4 = Ms.*2.0;
t5 = a.*2.0;
t6 = Mh+t4;
t7 = a+t2;
t8 = Mh.*t2;
t9 = Ms.*t7;
t10 = 1.0./t6;
t11 = t8+t9;
posCoM = [t10.*(t6.*x1-t11.*sin(x3)+Ms.*b.*sin(t3)),t10.*(t6.*x2+t11.*cos(x3)-Ms.*b.*cos(t3)),0.0];
