function velCoM = COM_vel_func(in1)
%COM_VEL_FUNC
%    VELCOM = COM_VEL_FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    06-Jan-2020 14:49:02

x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
t2 = x3+x4;
t3 = x7+x8;
velCoM = [x5+(t3.*cos(t2))./8.0-x7.*cos(x3).*(7.0./8.0),x6+(t3.*sin(t2))./8.0-x7.*sin(x3).*(7.0./8.0),0.0];
