function posFst = Foot_St_pos_func(in1,in2)
%FOOT_ST_POS_FUNC
%    POSFST = FOOT_ST_POS_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    11-May-2020 12:35:38

%Compass Gait Configuration file. Only needs state as inputs, parameters are already substituted in
x1 = in1(1,:);
x2 = in1(2,:);
posFst = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,x1,x2,0.0,1.0],[4,4]);
