function G = G_func(in1,in2)
%G_FUNC
%    G = G_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    08-Jun-2020 11:34:49

g = in2(:,1);
m = in2(:,2);
G = [0.0;g.*m];
