function Fval = Spring_Force_func(in1,in2)
%SPRING_FORCE_FUNC
%    FVAL = SPRING_FORCE_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    08-Jun-2020 11:34:49

L0 = in2(:,1);
k = in2(:,2);
x1 = in1(1,:);
x2 = in1(2,:);
xf = in1(5,:);
yf = in1(6,:);
Fval = k.*(L0-sqrt((x1-xf).^2+(x2-yf).^2));
