function jacob = Spring_Jacobian_func(in1,in2)
%SPRING_JACOBIAN_FUNC
%    JACOB = SPRING_JACOBIAN_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    08-Jun-2020 11:34:50

x1 = in1(1,:);
x2 = in1(2,:);
xf = in1(5,:);
yf = in1(6,:);
t2 = -xf;
t3 = -yf;
t4 = t2+x1;
t5 = t3+x2;
t6 = t4.^2;
t7 = t5.^2;
t8 = t6+t7;
t9 = 1.0./sqrt(t8);
jacob = [t4.*t9;t5.*t9];
