function G = G_func(in1,in2)
%G_FUNC
%    G = G_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    11-May-2020 12:35:35

%Compass Gait Configuration file. Only needs state as inputs, parameters are already substituted in
Mh = in2(:,2);
Ms = in2(:,3);
a = in2(:,4);
b = in2(:,5);
g = in2(:,6);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = x3+x4;
t3 = sin(t2);
G = [0.0;g.*(Mh+Ms.*2.0);-g.*(sin(x3).*(Ms.*(a.*2.0+b)+Mh.*(a+b))-Ms.*b.*t3);Ms.*b.*g.*t3];
